version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "bigNsmall517!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

  web:
    build: .
    ports:
      - "5000:80"
    depends_on:
      - sqlserver
